# Generated by Django 3.2.5 on 2021-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
