"""
Django settings for notes_app project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

try:
    from notes_app.local_settings import *
except ImportError:
    from notes_app.prod_settings import *
